//! Burn-surface audit: direct `burn`/`burn-ndarray` usage being retired in
//! favour of the Coeus autodiff component.
//!
//! Split out of the parent `migration_audit` module, which owns the shared
//! scan/allowlist machinery and the legacy-stack audit.

use super::{
    compare_with_allowlist, crate_name_from_path, has_any_manifest_dep, manifest_allowlist_entry,
    relative, source_allowlist_entry, visit_files, write_allowlist, SourceReference,
};
use anyhow::{bail, Context, Result};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const BURN_MANIFEST_DEPS: &[&str] = &["burn", "burn-ndarray"];

const BURN_SOURCE_TOKENS: &[&str] = &[
    "burn::",
    "burn_ndarray",
    "AutodiffBackend",
    "GradientsParams",
    "TensorData",
    "Shape::new",
    "Param<",
    "Conv1d",
    "Conv2d",
    "Conv3d",
    "BurnPINN",
    "BurnWave",
    "burn_wave_equation",
];

const BURN_ALLOWLIST_REL_PATH: &str = "xtask/burn_surface.allowlist";

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(crate) struct CrateBurnSurface {
    pub(crate) manifest_dependency: bool,
    pub(crate) source_reference_count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct BurnMigrationReport {
    pub(crate) manifest_dependencies: Vec<PathBuf>,
    pub(crate) source_references: Vec<SourceReference>,
    pub(crate) by_crate: BTreeMap<String, CrateBurnSurface>,
}

pub(crate) fn print_burn_migration_audit(root: &Path) -> Result<()> {
    let report = scan_burn_migration_surface(root)?;
    let diff = compare_with_allowlist(
        root,
        BURN_ALLOWLIST_REL_PATH,
        "refresh-burn-allowlist",
        &burn_allowlist_entries(&report),
    )?;

    println!("Burn migration audit");
    println!("====================");
    println!();
    println!(
        "Manifest files with Burn deps ({})",
        report.manifest_dependencies.len()
    );
    for path in &report.manifest_dependencies {
        println!("  - {}", path.display());
    }

    println!();
    println!(
        "Source files with Burn-surface tokens ({})",
        report.source_references.len()
    );
    for source in &report.source_references {
        println!("  - {} ({})", source.path.display(), source.count);
    }

    println!();
    println!("Crate summary:");
    for (name, surface) in &report.by_crate {
        println!(
            "  - {name}: burn(dep={}, tokens={})",
            surface.manifest_dependency, surface.source_reference_count
        );
    }

    println!();
    if diff.new_entries.is_empty() {
        println!("Allowlist status: clean");
    } else {
        println!(
            "Allowlist drift: {} new Burn surfaces not in {}",
            diff.new_entries.len(),
            BURN_ALLOWLIST_REL_PATH
        );
        for entry in &diff.new_entries {
            println!("  - {entry}");
        }
    }

    if !diff.stale_entries.is_empty() {
        println!();
        println!("Allowlist cleanup candidates (already migrated):");
        for entry in &diff.stale_entries {
            println!("  - {entry}");
        }
    }

    if !diff.new_entries.is_empty() {
        bail!(
            "Burn migration allowlist drift detected; run `cargo run -p xtask -- refresh-burn-allowlist` after intentional changes"
        );
    }

    Ok(())
}

pub(crate) fn refresh_burn_allowlist(root: &Path) -> Result<()> {
    let report = scan_burn_migration_surface(root)?;
    write_allowlist(
        root,
        BURN_ALLOWLIST_REL_PATH,
        "# Auto-generated by `cargo run -p xtask -- refresh-burn-allowlist`\n\
         # Each entry tracks an approved Burn surface during Coeus migration.\n",
        burn_allowlist_entries(&report),
    )
}

/// Allowlist entries the Burn scan reports: manifest and source sites.
fn burn_allowlist_entries(report: &BurnMigrationReport) -> BTreeSet<String> {
    let mut entries = BTreeSet::new();
    for path in &report.manifest_dependencies {
        entries.insert(manifest_allowlist_entry(path));
    }
    for source in &report.source_references {
        entries.insert(source_allowlist_entry(&source.path));
    }
    entries
}

pub(crate) fn scan_burn_migration_surface(root: &Path) -> Result<BurnMigrationReport> {
    let mut manifest_dependencies = Vec::new();
    let mut source_references = Vec::new();
    let mut by_crate = BTreeMap::<String, CrateBurnSurface>::new();

    visit_files(root, &mut |path| {
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            return Ok(());
        };

        if file_name == "Cargo.toml" {
            let text = fs::read_to_string(path)
                .with_context(|| format!("failed reading {}", path.display()))?;
            if has_any_manifest_dep(&text, BURN_MANIFEST_DEPS) {
                let rel = relative(root, path);
                if let Some(crate_name) = crate_name_from_path(root, path) {
                    by_crate.entry(crate_name).or_default().manifest_dependency = true;
                }
                manifest_dependencies.push(rel);
            }
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            let text = fs::read_to_string(path)
                .with_context(|| format!("failed reading {}", path.display()))?;
            let count = BURN_SOURCE_TOKENS
                .iter()
                .map(|token| text.matches(token).count())
                .sum::<usize>();
            if count > 0 {
                if let Some(crate_name) = crate_name_from_path(root, path) {
                    by_crate
                        .entry(crate_name)
                        .or_default()
                        .source_reference_count += count;
                }
                source_references.push(SourceReference {
                    path: relative(root, path),
                    count,
                });
            }
        }

        Ok(())
    })?;

    manifest_dependencies.sort();
    source_references.sort_by(|a, b| a.path.cmp(&b.path));

    Ok(BurnMigrationReport {
        manifest_dependencies,
        source_references,
        by_crate,
    })
}
