//! Dependency-migration audits for the workspace manifests and sources.
//!
//! Two surfaces are audited against committed allowlists: the legacy compute
//! stack (nalgebra/ndarray/burn/tokio/rayon/…) being retired in favour of the
//! Atlas providers, and the Burn surface being retired in favour of Coeus. Each
//! audit scans every manifest and `.rs` file under the workspace root, prints
//! the sites it finds, and fails when the scan reports a surface the allowlist
//! does not record (drift) — so an intentional change is recorded by re-running
//! the matching `refresh-*-allowlist` command.

use anyhow::{bail, Context, Result};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

mod burn;

pub(crate) use burn::{print_burn_migration_audit, refresh_burn_allowlist};

const LEGACY_MANIFEST_DEPS: &[&str] = &[
    "nalgebra",
    "nalgebra-sparse",
    "ndarray",
    "burn",
    "burn-ndarray",
    "tokio",
    "rayon",
    "approx",
    "num-traits",
    "rustfft",
];

const LEGACY_SOURCE_TOKENS: &[&str] = &[
    "nalgebra::",
    "ndarray::",
    "burn::",
    "burn_ndarray",
    "tokio::",
    "rayon::",
    "approx::",
    "num_traits::",
    "rustfft::",
];

const ATLAS_MANIFEST_DEPS: &[&str] = &["moirai", "leto", "hephaestus", "coeus"];

const ALLOWLIST_REL_PATH: &str = "xtask/legacy_surface.allowlist";

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SourceReference {
    pub(crate) path: PathBuf,
    pub(crate) count: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LegacyMigrationReport {
    pub(crate) manifest_dependencies: Vec<PathBuf>,
    pub(crate) source_references: Vec<SourceReference>,
    pub(crate) atlas_manifest_references: Vec<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct AllowlistDiff {
    new_entries: Vec<String>,
    stale_entries: Vec<String>,
}

pub(crate) fn print_legacy_migration_audit(root: &Path) -> Result<()> {
    let report = scan_legacy_migration_surface(root)?;
    let diff = compare_with_allowlist(
        root,
        ALLOWLIST_REL_PATH,
        "refresh-legacy-allowlist",
        &legacy_allowlist_entries(&report),
    )?;

    println!("Legacy migration audit");
    println!("======================");
    println!();
    println!(
        "Manifest files with legacy deps ({})",
        report.manifest_dependencies.len()
    );
    for path in &report.manifest_dependencies {
        println!("  - {}", path.display());
    }

    println!();
    println!(
        "Source files with legacy tokens ({})",
        report.source_references.len()
    );
    for source in &report.source_references {
        println!("  - {} ({})", source.path.display(), source.count);
    }

    println!();
    println!(
        "Manifest files already using Atlas deps ({})",
        report.atlas_manifest_references.len()
    );
    for path in &report.atlas_manifest_references {
        println!("  - {}", path.display());
    }

    println!();
    if diff.new_entries.is_empty() {
        println!("Allowlist status: clean");
    } else {
        println!(
            "Allowlist drift: {} new legacy surfaces not in {}",
            diff.new_entries.len(),
            ALLOWLIST_REL_PATH
        );
        for entry in &diff.new_entries {
            println!("  - {entry}");
        }
    }

    if !diff.stale_entries.is_empty() {
        println!();
        println!("Allowlist cleanup candidates (already migrated):");
        for entry in &diff.stale_entries {
            println!("  - {entry}");
        }
    }

    if !diff.new_entries.is_empty() {
        bail!(
            "legacy migration allowlist drift detected; run `cargo run -p xtask -- refresh-legacy-allowlist` after intentional changes"
        );
    }

    Ok(())
}

pub(crate) fn refresh_legacy_allowlist(root: &Path) -> Result<()> {
    let report = scan_legacy_migration_surface(root)?;
    write_allowlist(
        root,
        ALLOWLIST_REL_PATH,
        "# Auto-generated by `cargo run -p xtask -- refresh-legacy-allowlist`\n\
         # Each entry tracks an approved legacy surface during Atlas migration.\n",
        legacy_allowlist_entries(&report),
    )
}

/// Allowlist entries the legacy scan reports: manifest and source sites.
fn legacy_allowlist_entries(report: &LegacyMigrationReport) -> BTreeSet<String> {
    let mut entries = BTreeSet::new();
    for path in &report.manifest_dependencies {
        entries.insert(manifest_allowlist_entry(path));
    }
    for source in &report.source_references {
        entries.insert(source_allowlist_entry(&source.path));
    }
    entries
}

pub(crate) fn scan_legacy_migration_surface(root: &Path) -> Result<LegacyMigrationReport> {
    let mut manifest_dependencies = Vec::new();
    let mut source_references = Vec::new();
    let mut atlas_manifest_references = Vec::new();

    visit_files(root, &mut |path| {
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            return Ok(());
        };

        if file_name == "Cargo.toml" {
            let text = fs::read_to_string(path)
                .with_context(|| format!("failed reading {}", path.display()))?;
            let rel = relative(root, path);
            if has_any_manifest_dep(&text, LEGACY_MANIFEST_DEPS) {
                manifest_dependencies.push(rel.clone());
            }
            if has_any_manifest_dep(&text, ATLAS_MANIFEST_DEPS) {
                atlas_manifest_references.push(rel);
            }
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            let text = fs::read_to_string(path)
                .with_context(|| format!("failed reading {}", path.display()))?;
            let count = legacy_source_reference_count(&text);
            if count > 0 {
                source_references.push(SourceReference {
                    path: relative(root, path),
                    count,
                });
            }
        }

        Ok(())
    })?;

    manifest_dependencies.sort();
    atlas_manifest_references.sort();
    source_references.sort_by(|a, b| a.path.cmp(&b.path));

    Ok(LegacyMigrationReport {
        manifest_dependencies,
        source_references,
        atlas_manifest_references,
    })
}

fn legacy_source_reference_count(text: &str) -> usize {
    LEGACY_SOURCE_TOKENS
        .iter()
        .map(|token| {
            text.match_indices(token)
                // NumPy's PyO3 facade re-exports ndarray types. It is an FFI
                // boundary, not a direct legacy-compute dependency.
                .filter(|(offset, _)| {
                    *token != "ndarray::" || !text[..*offset].ends_with("numpy::")
                })
                .count()
        })
        .sum()
}

/// Diff a scan's entries against the committed allowlist at
/// `allowlist_rel_path`, naming `refresh_command` in the error when the file is
/// missing. Shared by both migration audits; the two callers differ only in the
/// allowlist path and the entries they collect.
fn compare_with_allowlist(
    root: &Path,
    allowlist_rel_path: &str,
    refresh_command: &str,
    current: &BTreeSet<String>,
) -> Result<AllowlistDiff> {
    let allowlist_path = root.join(allowlist_rel_path);
    if !allowlist_path.exists() {
        bail!(
            "missing {}; run `cargo run -p xtask -- {refresh_command}`",
            allowlist_path.display()
        );
    }

    let allowed = load_allowlist(&allowlist_path)?;
    let new_entries = current.difference(&allowed).cloned().collect();
    let stale_entries = allowed.difference(current).cloned().collect();
    Ok(AllowlistDiff {
        new_entries,
        stale_entries,
    })
}

/// Write `entries`, one per line under `header`, to the allowlist at
/// `allowlist_rel_path`. Shared by the two `refresh-*-allowlist` commands.
fn write_allowlist(
    root: &Path,
    allowlist_rel_path: &str,
    header: &str,
    entries: BTreeSet<String>,
) -> Result<()> {
    let allowlist_path = root.join(allowlist_rel_path);
    if let Some(parent) = allowlist_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed creating {}", parent.display()))?;
    }

    let mut body = String::from(header);
    for entry in entries {
        body.push_str(&entry);
        body.push('\n');
    }

    fs::write(&allowlist_path, body)
        .with_context(|| format!("failed writing {}", allowlist_path.display()))?;
    println!("Updated {}", allowlist_path.display());
    Ok(())
}

fn load_allowlist(path: &Path) -> Result<BTreeSet<String>> {
    let text =
        fs::read_to_string(path).with_context(|| format!("failed reading {}", path.display()))?;
    let mut entries = BTreeSet::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        entries.insert(trimmed.to_owned());
    }
    Ok(entries)
}

fn has_any_manifest_dep(text: &str, deps: &[&str]) -> bool {
    text.lines().any(|line| {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with('[') {
            return false;
        }

        let Some((raw_key, _)) = trimmed.split_once('=') else {
            return false;
        };

        let key = raw_key.trim();
        deps.iter()
            .any(|dep| key == *dep || key == format!("{dep}.workspace"))
    })
}

fn visit_files(root: &Path, visit: &mut impl FnMut(&Path) -> Result<()>) -> Result<()> {
    if should_skip(root) {
        return Ok(());
    }

    for entry in fs::read_dir(root).with_context(|| format!("failed reading {}", root.display()))? {
        let entry = entry?;
        let path = entry.path();
        if should_skip(&path) {
            continue;
        }
        if path.is_dir() {
            visit_files(&path, visit)?;
        } else {
            visit(&path)?;
        }
    }

    Ok(())
}

fn should_skip(path: &Path) -> bool {
    matches!(
        path.file_name().and_then(|name| name.to_str()),
        Some(".git" | "target" | "xtask")
    )
}

fn relative(root: &Path, path: &Path) -> PathBuf {
    path.strip_prefix(root).unwrap_or(path).to_path_buf()
}

/// The `crates/<name>` or `xtask` owner of a path under the workspace root.
fn crate_name_from_path(root: &Path, path: &Path) -> Option<String> {
    let rel = path.strip_prefix(root).ok()?;
    let mut parts = rel.components();
    match parts.next()?.as_os_str().to_str()? {
        "crates" => parts.next()?.as_os_str().to_str().map(str::to_owned),
        "xtask" => Some("xtask".to_owned()),
        _ => None,
    }
}

fn manifest_allowlist_entry(path: &Path) -> String {
    format!("manifest:{}", normalized(path))
}

fn source_allowlist_entry(path: &Path) -> String {
    format!("source:{}", normalized(path))
}

fn normalized(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}
